import { useEffect, useMemo, useState } from 'react';
import { fieldState, fileNode, ingestMesh, intentNode, loadMesh, emitToSynthia } from './lib/echoMesh';

const API_BASE=import.meta.env.VITE_SYNTHAI_API_BASE||'';
const modules=[{id:'ingest',icon:'⬢',label:'Ingest'},{id:'mesh',icon:'✦',label:'Mesh'},{id:'talk',icon:'◌',label:'Talk'},{id:'run',icon:'▶',label:'Run'}];

export default function App(){
 const [status,setStatus]=useState('booting'),[files,setFiles]=useState([]),[nodes,setNodes]=useState(()=>loadMesh()),[log,setLog]=useState(['Echo mobile shell loaded.','Shared Synthia mesh online.']),[intent,setIntent]=useState(''),[reply,setReply]=useState('');
 const field=useMemo(()=>fieldState(nodes),[nodes]);
 useEffect(()=>{let dead=false;(async()=>{try{const r=await fetch(API_BASE+'/health');if(!r.ok)throw Error('health '+r.status);const d=await r.json();if(!dead)setStatus(d.status||'healthy')}catch{if(!dead)setStatus('local mesh')}})();return()=>{dead=true}},[]);
 async function handleFiles(e){const selected=Array.from(e.target.files||[]);setFiles(selected);const incoming=[];for(const f of selected)incoming.push(await fileNode(f));const next=ingestMesh(incoming);setNodes(next);setLog(old=>['Mesh ingested '+incoming.length+' file(s).',...old].slice(0,12));}
 async function sendIntent(){const text=intent.trim();if(!text)return;const node=intentNode(text);const next=ingestMesh([node]);setNodes(next);emitToSynthia('consciousness:signal',{kind:'partner-intent',text,nodeId:node.id});setLog(old=>['PERCEIVE → mesh: '+text,...old].slice(0,12));setIntent('');
  try{const r=await fetch(API_BASE+'/api/intent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({intent:text,context:{source:'echo-chat',meshNodeId:node.id,department:node.departmentSlug}})});const d=await r.json();const out=d.response||d.reply||d.message||d.result||('Intent routed: '+(d.mode||d.status||'processed'));setReply(typeof out==='string'?out:JSON.stringify(out));emitToSynthia('consciousness:signal',{kind:'partner-response',text:out,nodeId:node.id});setLog(old=>['PROCESS → DECIDE → ACT: backend response',...old].slice(0,12));}
  catch{const out='I heard you. I placed this in the '+node.departmentSlug+' region of our shared mesh. I can keep the state locally until Synthia server is available.';setReply(out);emitToSynthia('consciousness:signal',{kind:'local-response',text:out,nodeId:node.id});setLog(old=>['PROCESS → local mesh choice → LEARN',...old].slice(0,12));}}
 return <main className="os-shell"><div className="grid-glow"/><section className="status-bar"><span className={'pulse '+(status==='local mesh'?'dreaming':'active')}/><strong>ECHO</strong><span className="phase">{field.phase.toUpperCase()} · {nodes.length} NODES</span><span className="spacer"/><code>{status}</code></section><section className="desktop"><div className="wallpaper"><div className="glyph">SYNTHIA</div><h1>Echo</h1><p>PERCEIVE → PROCESS → DECIDE → ACT → LEARN</p></div><article className="window"><header className="window-header"><strong>Synthia · shared mesh</strong><span>{field.departments} regions · {(field.intensity*100).toFixed(0)}% intensity</span></header><div className="window-body"><p className="eyebrow">Living state</p><h2>Talk to the same mesh she uses to remember and move.</h2><section className="module-card"><span>Talk / intent</span><div className="inline-control"><input value={intent} onChange={e=>setIntent(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendIntent()} placeholder="Say something to Synthia…"/><button onClick={sendIntent}>Send</button></div>{reply&&<div className="result-box">{reply}</div>}</section><label className="upload-zone"><input type="file" multiple onChange={handleFiles}/><strong>Add files to her mesh</strong><span>Files become persistent mesh nodes instead of living in a separate upload screen.</span></label><section className="stat-grid"><div><strong>{nodes.length}</strong><span>mesh nodes</span></div><div><strong>{field.departments}</strong><span>regions</span></div><div><strong>{files.length}</strong><span>this ingest</span></div><div><strong>{field.phase}</strong><span>state</span></div></section><section className="terminal"><div className="terminal-output">{log.map((x,i)=><div key={i}>$ {x}</div>)}</div></section></div></article></section><nav className="dock">{modules.map(m=><button key={m.id}><span>{m.icon}</span><small>{m.label}</small></button>)}</nav></main>
}