const KEY='echo:mesh:v1',OUTBOX='echo:synthia:outbox:v1';
const uid=(p='node')=>globalThis.crypto?.randomUUID?.()||p+'_'+Date.now()+'_'+Math.random().toString(36).slice(2);
export function loadMesh(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
const save=n=>localStorage.setItem(KEY,JSON.stringify(n.slice(0,300)));
function route(t=''){const r={consciousness:['consciousness','resonance','morph','mrnn','neural','brain','mesh','klein','autoling'],engineering:['api','code','server','database','react','mcp','javascript','python'],research:['research','paper','notes','analysis','study'],creative:['design','visual','image','video','audio'],operations:['workflow','process','task','system'],strategy:['plan','roadmap','launch','growth','business']},h=t.toLowerCase();let b='archive',s=0;for(const[k,v]of Object.entries(r)){const n=v.reduce((a,x)=>a+(h.includes(x)?1:0),0);if(n>s){b=k;s=n}}return b}
export function emitToSynthia(type,payload){const m={id:uid('msg'),type,source:'echo',target:'synthia',payload,timestamp:new Date().toISOString(),trace:['SynthAIPRODeploy','didactic-octo-disco']};let o=[];try{o=JSON.parse(localStorage.getItem(OUTBOX)||'[]')}catch{}localStorage.setItem(OUTBOX,JSON.stringify([...o,m].slice(-500)));window.dispatchEvent(new CustomEvent('synthia:morph-message',{detail:m}));return m}
export function intentNode(text){const now=new Date().toISOString();return{id:uid('intent'),title:text.slice(0,72),sourceType:'intent/user',kind:'intent',departmentSlug:route(text),content:text,summary:text,state:'classified',metadata:{source:'echo-chat'},edges:[],createdAt:now,updatedAt:now}}
export async function fileNode(f){const now=new Date().toISOString(),txt=/\.(md|txt|json|js|ts|tsx|jsx|css|html|py|csv|ya?ml)$/i.test(f.name),content=txt?await f.text():null,kind=/\.zip$/i.test(f.name)?'archive':txt?'text':'binary';return{id:uid(),title:f.name,sourceType:f.type||'application/octet-stream',kind,departmentSlug:route(f.name+' '+(content||'')),content,summary:content?.replace(/\s+/g,' ').slice(0,320)||kind+' · '+f.size+' bytes',state:'classified',metadata:{size:f.size,lastModified:f.lastModified},edges:[],createdAt:now,updatedAt:now}}
export function ingestMesh(incoming){const all=[...incoming,...loadMesh()],nodes=all.map(n=>({...n,edges:all.filter(x=>x.id!==n.id&&x.departmentSlug===n.departmentSlug).slice(0,3).map(x=>x.id)}));save(nodes);incoming.forEach(n=>emitToSynthia('node:ingested',n));return nodes}
export function fieldState(nodes=loadMesh()){const total=nodes.length,departments=new Set(nodes.map(n=>n.departmentSlug)).size,mass=nodes.reduce((a,n)=>a+(n.content?.length||0),0);return{total,departments,intensity:Math.min(1,Math.log10(mass+10)/6),phase:total===0?'dormant':total<4?'observant':total<10?'active':'resonant'}}
